### PR TITLE
37 report i18n

### PR DESCRIPTION
**Pull request by cezio**
fix https://github.com/geosolutions-it/ckanext-provbz/issues/37

### CODE REVIEW

**Comment by tdipisa** [comment]
@cezio

1. 
> Starting from the URL below
http://test-dati.retecivica.bz.it/it/report/resources-format?res_format=WMS
and changing language an error occurs (400 bad request, Option not allowed by report: res_format=WMS)
> Starting from the URL below
http://test-dati.retecivica.bz.it/it/report/broken-links?org=provincia-autonoma-di-bolzano-alto-adige-astat
and changing language an error occurs (400 bad request, Option not allowed by report: org=provincia-autonoma-di-bolzano-alto-adige-astat)

Not working, If I change language I'm redirected to the home page

2. 

In licenses report is also missing the label below as we have in the other reports

**Indice di tutte le organizzazioni**

3. 
>  Link to report section in home footer, visible only to admin

It seems to be missing 

4. 
Then the following strings aren't traslated both in IT and DE (you can see some samples [here](http://188.165.62.180/it/report/broken-links?org=pab-agenzia-provinciale-per-l-ambiente)):

Resource's URL is invalid for OWS service, however it responds with correct HTTP response.

Provided url doesn't work as OWS endpoint

**Comment by cezio** [comment]
> 1. (bad redirection from language selection)

The fix was implemented in provbz extension, but it was relying on `helpers.current_url()`. CKAN 2.4.0 doesn't have current_url() helper:
https://github.com/ckan/ckan/blob/ckan-2.4.0/ckan/lib/helpers.py#L277-L280
while 2.4.9 has it:
https://github.com/ckan/ckan/blob/ckan-2.4.9/ckan/lib/helpers.py#L305-L313

Fix was introduced by
https://github.com/ckan/ckan/commit/109d47c1fe852085eb9bf3ba8e34d6bc6e57e3b1


Because we're basically backporting fix from the same minor version (2.4.x), can we upgrade ckan to 2.4.9 ? Then fix in provbz won't be needed.


> 2.

Fixed. To be precise here, link would be shown if organization would be selected.
image

> 3. Link to report section in home footer, visible only to admin, It seems to be missing

This was because of order of plugins in config. Report plugins override footer template, and should be before provbz plugin. 
image

**Comment by cezio** [comment]
> 4. 
> Then the following strings aren't traslated both in IT and DE (you can see some samples here):
> Resource's URL is invalid for OWS service, however it responds with correct HTTP response.
> Provided url doesn't work as OWS endpoint

I've digged into this. The problem was message template was translated, but report generation was rendering this template with parameters, so final string was different from msgid. I've added message compiling in view template, and separate row variables for rendered messages (`msg_rendered` and `msg_raw` with raw error message if available). Also, I've added error messages to translation set, so there's sibling PR with updated translations: https://github.com/geosolutions-it/ckanext-provbz/pull/45

**Comment by cezio** [comment]
> 1. (bad redirection from language selection)

I've improved current url handling. Sibling PR: https://github.com/geosolutions-it/ckanext-provbz/pull/44

**Pull request merged**
