### PR TITLE
updated translations #2

### LINKED ISSUE #2: Report translations
i18n files should be provided at least for:
Italian
English
Deutch

### PR DESCRIPTION
**Pull request by cezio**
fix #2

### CODE REVIEW

**Review by tdipisa — CHANGES_REQUESTED** [review]
@cezio the travis build fails due to the requirements.txt file seems to be wrong. Can you fix this please?

**Comment by cezio** [comment]
Indeed, ckanext-report is not packaged and exposed in pypi. Will use git link in requirements then.

**Comment by cezio** [comment]
travis is fixed.

**Review by tdipisa — APPROVED** [review]

**Comment by tdipisa** [comment]
closed in favour of #9

**Pull request closed without merging**
