### PR TITLE
Ui improvements

### LINKED ISSUE #10: Improve the broken-link section
Improve the presentation of the report to allow the user to better navigate the available information:

- [x] remove the white column on the left and remove the gray line strip on the top
- [x] provide a table view like [here](https://data.gov.uk/data/report/broken-links)  that lists the organizzations with the conresponding counters (dataset with broken links/broken links and %). 
- [x] Then the user can drilldown by selecting one organization from the table or selecting her from the dropdown filter to show the list of involved resources/links like [here](https://data.gov.uk/data/report/broken-links/joint-nature-conservation-committee) (we can avoid to introduce the last 4 columns). In this section we can also think to maintain what we already are reporting for OWS resources in a specific column and the HTTP code: 

ows

- [x] show the general percentage of the broken links in respect of the checked resources in both sections

gs-rp-1

### LINKED ISSUE #11: Improve the resource format section
Improve the presentation of the report to allow the user to better navigate the available information:

- [x] remove the white column on the left and remove the gray line strip on the top
- [x] maintain the table view that we have now but with an additional capability. When the user click on the format link another table appears containing the list of the involved resources like [this](https://data.gov.uk/data/report/publisher-resources/cabinet-office). In that section the user can always filter by organization
- [x] since we added this extension we have a **not-specified** format in the main ckan facet:

gs-report-2

that should be removed

### LINKED ISSUE #12: Improve the licenses section
Improve the presentation of the report to allow the user to better navigate the available information:

- [x] remove the white column on the left and remove the gray line strip on the top
- [x] add a new first column containing the complete name of the license, now we have only the identifier: cc-zero is for example **Creative Commons CC0**
- [x] review the count:
cc-zero is 239 but should be 240
notspecified is 1 but its seems that we don't have [any of them](http://188.165.62.180/dataset?license_id=notspecified)

### PR DESCRIPTION
**Pull request by cezio**
fix #10 
fix #11 
fix #12 

This is still WiP
Functionality works, reports are generated as overview and per-organization (or per-format) reports. You should rerun reports generation after updating code.

### CODE REVIEW

**Comment by tdipisa** [comment]
@cezio 

**BROKEN LINKS**
links

**LICENSES**
licenses

**RESOURCES FORMAT**
resources

**Review by tdipisa — COMMENTED** [review]
@cezio 

**BROKEN LINKS**
links

**LICENSES**
licenses

**RESOURCES FORMAT**
resources

**Comment by cezio** [comment]
image


This is generated in template, it's a list of params that don't have any input widget, so they're just listed. I can hide those values.

https://github.com/cezio/ckanext-gsreport/blob/ui_improvements/ckanext/gsreport/templates/report/view.html#L53-L66

**Review by tdipisa — COMMENTED** [review]
fix

**Pull request merged**
